### ISSUE TITLE
server.config

### ISSUE THREAD

**Issue by poojakar** [leesper/couchdb-golang#2]
I want to know what is the parameter we are passing to config method? There is give config(node string). Please tell me what should be the node string? Give me the example.

**Comment by leesper** [comment]
@poojakar Hi, CouchDB 2.x supports clustering so that the _config method cannot be directly access by simply calling, we have to specify what node in cluster do we want to see the configuration, so we can call the Membership() method of Server to get the nodes to put in "node String" . Please refer at:

1. [stackoverflow](https://stackoverflow.com/questions/41618207/couchdb-requesting-config-and-log-gives-404)
2. [couchdb doc](http://docs.couchdb.org/en/2.0.0/api/server/configuration.html)

Thank you : ) !

**Comment by poojakar** [comment]
@leesper Thank you so much. When i call Membership() method, i get
 [bigcouch@bigcouch1-2600-prov-cert1.cn.ooma.com bigcouch@bigcouch1-2600-prov-cert2.cn.ooma.com bigcouch@bigcouch1-2600-prov-cert3.cn.ooma.com]
[bigcouch@bigcouch1-2600-prov-cert1.cn.ooma.com bigcouch@bigcouch1-2600-prov-cert2.cn.ooma.com bigcouch@bigcouch1-2600-prov-cert3.cn.ooma.com]

okay?
Then i m trying to call Config("bigcouch@bigcouch1-2600-prov-cert1.cn.ooma.com") method,then it gives me error "status 404 - not found"

Why is it so?

**Comment by leesper** [comment]
@poojakar well... that's weird, but I only write unit tests in single mode...I'm not good at solving your problems : (, could you please refer my server_test.go file, there is a unit test there for Config, maybe you can add some tests more thoroughly, I'll really appreciate it.

**Comment by poojakar** [comment]
@leesper Does this package supports for couchdb v.1.1.1?

**Comment by leesper** [comment]
@poojakar The oldest version I've seen is CouchDB 1.6.x, I'm not sure if it works well with before, I created this project to support out business at the very beginning, but later on we decided to use mongodb instead, so it is left unused since then, sorry ...

**Comment by poojakar** [comment]
@leesper Thanks a lot :)
